import Head from 'next/head';
import React from 'react';

import { Login } from '../../components/pages/auth/login';
import { Register } from '../../components/pages/auth/register';
import { Categories } from '../../components/shared/Categories';
import { Header } from '../../components/shared/Header';

const Auth = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Header />
      {/* Categories */}
      <Categories />
      <div className="mx-auto mt-128  flex max-w-[1400px] items-center gap-[10px] px-16 py-16 text-text-sm" />
      <div className="mx-auto my-40 flex w-full max-w-[1400px] gap-[20px]">
        {/* Login */}
        <Login />

        <div className="flex h-[500px] w-[2px] items-center justify-center bg-gray-500">
          <div className="flex items-center justify-center rounded-full border-2 border-gray-500 bg-white p-8">
            <p className="text-text-sm">Ou</p>
          </div>
        </div>
        {/* Register */}
        <Register />
      </div>
      {/* Route */}
    </main>
  </>
);
export default Auth;
