import axios from 'axios';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useState } from 'react';
import { BiX } from 'react-icons/bi';

import { Categories } from '../../components/shared/Categories';
import { Header } from '../../components/shared/Header';
import { CartItem, useCart } from '../../context/Cart/CartContext';

const Cart = () => {
  const { cartItems, addItem, removeItem } = useCart();

  const [coupon, setCoupon] = useState('');

  const handleCoupon = async () => {
    await axios
      .get(`http://localhost:5000/coupon/${coupon}`)
      .then(() => console.log('SUCCESS'))
      .catch(() => console.log('ERROR'));
  };
  const updateCart = (
    QT: number,
    itemQt: number,
    id: string,
    item: CartItem
  ) => {
    if (itemQt > QT) {
      removeItem(id, 1);
    }
    if (itemQt < QT) {
      addItem(item, 1);
    }
  };

  function calculateTotal() {
    const total = cartItems.reduce(
      (acc, item) => acc + item.price * item.quantity,
      0
    );

    return (total + 50).toFixed(2);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        {/* Categories */}
        <Categories />
        <h1 className="text-display-md text-center py-40">Cart</h1>
        <div className="max-w-[1200px] w-full mx-auto">
          {/* Heading */}
          {cartItems?.length > 0 && (
            <div className="flex border-b-[1px] pb-4 border-gray-500 justify-between">
              <p>Product</p>
              <div className="flex justify-between w-[25%]">
                <p>Price</p>
                <p>Quantity</p>
                <p>Subtotal</p>
              </div>
            </div>
          )}
          {/*  Item */}
          {cartItems.length <= 0 ? (
            <div>
              <h1 className="px-24 text-center py-40 text-display-lg bg-yellow-500">
                Your cart is currently empty.
              </h1>
              <Link href="/shop">
                <button
                  type="button"
                  className="bg-gray-500 px-24 py-8 rounded-full my-20 mx-auto block"
                >
                  Return To Shop
                </button>
              </Link>
            </div>
          ) : (
            cartItems.map((item) => (
              <div className="flex items-center border-b-[1px] pb-4 border-gray-500 justify-between">
                <div className="flex items-center gap-[40px]">
                  <BiX
                    className="w-[25px] h-[25px] cursor-pointer"
                    onClick={() => removeItem(item.id, 999)}
                  />
                  <Image
                    src={item.image}
                    width={150}
                    height={150}
                    alt=""
                    className="max-w-[150px]"
                  />
                  <h1>{item.name}</h1>
                </div>
                <div className="flex items-center justify-between  w-[25%]">
                  <p>{item.price} DT</p>
                  <input
                    min={0}
                    type="number"
                    defaultValue={item.quantity}
                    onChange={(e) =>
                      updateCart(
                        parseInt(e.currentTarget.value, 10),
                        item.quantity,
                        item.id,
                        item
                      )
                    }
                    className="block border-[1px] border-gray-400 rounded-[12px] py-4 px-8 w-[50px] "
                  />
                  <p>{(item.price * item.quantity).toFixed(2)} DT</p>
                </div>
              </div>
            ))
          )}

          {/*  Button */}
          {cartItems.length > 0 && (
            <div className="w-full flex flex-col items-end justify-end">
              <div className="flex justify-between items-center w-full">
                <div className="relative flex h-[50px] ">
                  <input
                    value={coupon}
                    onChange={(e) => setCoupon(e.currentTarget.value)}
                    type="text"
                    maxLength={10}
                    placeholder="coupon"
                    className="px-24 h-[50px] py-8 rounded-full border-2"
                  />
                  <button
                    onClick={handleCoupon}
                    className="absolute w-[40%] h-[50px] bg-dark-500 left-[200px] top-0 text-white px-24  rounded-r-full"
                  >
                    Apply Coupon
                  </button>
                </div>
                <Link
                  href={{
                    pathname: '/checkout',
                    query: { coupon },
                  }}
                >
                  <button
                    type="button"
                    className="bg-yellow-500 px-24 py-8 font-semibold rounded-full my-20 ml-auto block"
                  >
                    Proceed to Checkout
                  </button>
                </Link>
              </div>
              {/* Cart Total */}
              <div>
                <h1 className="text-text-xl my-20 font-medium border-b-[2px] border-yellow-500">
                  Cart Total
                </h1>
                <div className="flex gap-[250px] items-center border-b-[1px] border-gray-500 py-8 justify-between">
                  <p className="text-text-sm font-semibold">Subtotal</p>
                  <p className="text-text-sm text-gray-400">
                    {calculateTotal()} DT
                  </p>
                </div>
                <div className="flex gap-[250px] items-center justify-between border-b-[1px] border-gray-500 py-8">
                  <p className="text-text-sm font-semibold">Shipping</p>
                  <p className="text-text-sm text-gray-400">50 DT</p>
                </div>
                <div className="flex gap-[250px] items-center justify-between border-b-[1px] border-gray-500 py-8">
                  <p className="text-text-sm font-semibold">Total</p>
                  <p className="text-text-sm font-semibold">
                    {calculateTotal()} DT
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
        {/* Route */}
      </main>
    </>
  );
};

export default Cart;
