import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { BiX } from 'react-icons/bi';

import Prod from '@/images/Product.png';

import { Categories } from '../../components/shared/Categories';
import { Header } from '../../components/shared/Header';
import { useCart } from '../../context/Cart/CartContext';

const Cart = () => {
  const { cartItems } = useCart();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        {/* Categories */}
        <Categories />
        <h1 className="text-display-md text-center py-40">Cart</h1>
        <div className="max-w-[1200px] w-full mx-auto">
          {/* Heading */}
          {cartItems.length > 0 && (
            <div className="flex border-b-[1px] pb-4 border-gray-500 justify-between">
              <p>Product</p>
              <div className="flex justify-between w-[25%]">
                <p>Price</p>
                <p>Quantity</p>
                <p>Subtotal</p>
              </div>
            </div>
          )}
          {/*  Item */}
          {cartItems.length <= 0 ? (
            <div>
              <h1 className="px-24 text-center py-40 text-display-lg bg-yellow-500">
                Your cart is currently empty.
              </h1>
              <button
                type="button"
                className="bg-gray-500 px-24 py-8 rounded-full my-20 mx-auto block"
              >
                Return To Shop
              </button>
            </div>
          ) : (
            cartItems.map((item) => (
              <div className="flex items-center border-b-[1px] pb-4 border-gray-500 justify-between">
                <div className="flex items-center gap-[40px]">
                  <BiX className="w-[25px] h-[25px]" />
                  <Image src={Prod} alt="" className="max-w-[150px]" />
                  <h1>{item.name}</h1>
                </div>
                <div className="flex items-center justify-between  w-[25%]">
                  <p>${item.price}</p>
                  <input
                    min={1}
                    type="number"
                    value={1}
                    onChange={() => {}}
                    className="block border-[1px] border-gray-400 rounded-[12px] py-4 px-8 w-[50px] "
                  />
                  <p>${item.price * item.quantity}</p>
                </div>
              </div>
            ))
          )}

          {/*  Button */}
          {cartItems.length > 0 && (
            <>
              <button
                type="button"
                className="bg-gray-500 px-24 py-8 rounded-full my-20 ml-auto block"
              >
                Update Cart
              </button>
              <button
                type="button"
                className="bg-yellow-500 px-24 py-8 font-semibold rounded-full my-20 ml-auto block"
              >
                Proceed to Checkout
              </button>
            </>
          )}
        </div>
        {/* Route */}
      </main>
    </>
  );
};

export default Cart;
