import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import { BiChevronRight } from 'react-icons/bi';

import { Filter } from '../../components/pages/shop/Filter';
import { ShopHeader } from '../../components/pages/shop/Header';
import { SideCategories } from '../../components/pages/shop/SideCategories';
import { Categories } from '../../components/shared/Categories';
import { Header } from '../../components/shared/Header';
import { ProductCard } from '../../components/shared/ProductCard';
import { Product } from '../../types/Product';

const Shop = ({
  data,
  transformedOptions,
}: {
  data: Product[];
  transformedOptions: { value: string; label: string }[];
}) => {
  const router = useRouter();

  const pathQuery = router.query;
  const [sort, setSort] = useState('high');

  const [price, setPrice] = useState([
    data.reduce((min, item) => (item.price < min.price ? item : min)).price,
    data.reduce((max, item) => (item.price > max.price ? item : max)).price,
  ]);
  const [selectedCategorie, setSelectedCategorie] = useState(
    pathQuery.category ? pathQuery.category : 'all'
  );
  let filtredItems = data.filter((item) =>
    item.price >= price[0] &&
    item.price <= price[1] &&
    selectedCategorie === 'all'
      ? true
      : // eslint-disable-next-line no-underscore-dangle
        item.categorie._id === selectedCategorie
  );

  if (pathQuery.word) {
    filtredItems = filtredItems.filter((item) =>
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      item.name.toLowerCase().includes(pathQuery?.word?.toLowerCase())
    );
    console.log('AWKA', filtredItems);
  }
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        {/* Categories */}
        <Categories />
        <div className="max-w-[1400px] mt-112  text-text-sm gap-[10px] px-16 flex items-center mx-auto py-16">
          <h1>Home</h1>
          <BiChevronRight className="w-[20px] h-[20px]" />
          <h1>Shop</h1>
        </div>
        <div className="w-full flex max-w-[1400px] mx-auto">
          {/* Filter */}
          <div className="w-[20%]">
            <SideCategories
              options={transformedOptions}
              setSelectedCategorie={setSelectedCategorie}
            />
            <Filter data={data} setPrice={setPrice} price={price} />
          </div>
          <div className="w-[80%] mx-40">
            <ShopHeader setSort={setSort} />
            {pathQuery.word && (
              <h1 className="pb-14">Results for {pathQuery.word} :</h1>
            )}
            <div className="grid grid-cols-4 gap-[0px]">
              {filtredItems
                .sort((a, b) =>
                  sort === 'low' ? a.price - b.price : b.price - a.price
                )
                .map((prod) => (
                  <ProductCard data={prod} />
                ))}
            </div>
          </div>
        </div>
        {/* Route */}
      </main>
    </>
  );
};
Shop.getInitialProps = async () => {
  const res = await axios
    .get('http://localhost:5000/Product/getall')
    .catch((error) => {
      console.error(error);
    });

  const data = await res?.data;

  const response = await axios.get('http://localhost:5000/categorie/getall'); // replace with your API endpoint
  const transformedOptions = response.data.map((option: any) => ({
    // eslint-disable-next-line no-underscore-dangle
    value: option._id,
    label: option.name,
  }));

  return { data, transformedOptions };
};
export default Shop;
