import Head from 'next/head';
import React from 'react';

import { Hero } from '../../components/pages/Product/Hero';
import { Reviews } from '../../components/pages/Product/Reviews';
import { Stats } from '../../components/pages/Product/Stats';
import { Categories } from '../../components/shared/Categories';
import { Footer } from '../../components/shared/Footer';
import { Header } from '../../components/shared/Header';
import { Category } from '../../types/Category';
import { Product as ProdType } from '../../types/Product';
import { SousCategory } from '../../types/SousCategory';
import { axiosDev } from '../api/axios';

const Product = ({
  initialProducts,
  initialCategories,
  initialSousCategories,
}: {
  initialProducts: ProdType;
  initialCategories: Category[];
  initialSousCategories: SousCategory[];
}) => (
  <>
    <Head>
      <title>{initialProducts.name}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Header />
      {/* Categories */}
      <Categories
        categories={initialCategories}
        sousCategories={initialSousCategories}
      />
      {/* Route */}
      <div className="mt-112  w-full" />

      {/*  Hero */}
      <Hero prod={initialProducts} />
      <div className="w-full bg-gray-300 py-40">
        {/* <Description /> */}
        <Stats prod={initialProducts} />
        <Reviews prod={initialProducts} />
      </div>
      <Footer categories={initialCategories} />
    </main>
  </>
);

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
Product.getInitialProps = async ({ query }) => {
  try {
    const [ProdsRes, CatRes, SousCatRes] = await Promise.all([
      axiosDev.get(`/Product/${query.id}`),
      axiosDev.get('/categorie/getall'),
      axiosDev.get('/sousCat/getall'),
    ]);

    const initialProducts = ProdsRes.data;
    const initialCategories = CatRes.data;
    const initialSousCategories = SousCatRes.data;

    return {
      initialProducts,
      initialCategories,
      initialSousCategories,
    };
  } catch (error) {
    console.error(error);
    return {
      initialProducts: [],
      initialCategories: [],
      initialSousCategories: [],
    };
  }
};
export default Product;
