import Head from 'next/head';
import React from 'react';

import { Hero } from '../../components/pages/Product/Hero';
import { Reviews } from '../../components/pages/Product/Reviews';
import { Route } from '../../components/pages/Product/Route';
import { Stats } from '../../components/pages/Product/Stats';
import { Categories } from '../../components/shared/Categories';
import { Header } from '../../components/shared/Header';
import { Product as ProdType } from '../../types/Product';
import axiosProduction from '../api/axios';

const Product = ({ data }: { data: ProdType }) => (
  <>
    <Head>
      <title>{data.name}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Header />
      {/* Categories */}
      <Categories />
      {/* Route */}
      <div className="mt-112  w-full" />
      <Route />
      {/*  Hero */}
      <Hero prod={data} />
      <div className="w-full bg-gray-300 py-40">
        {/* <Description /> */}
        <Stats prod={data} />
        <Reviews prod={data} />
      </div>
    </main>
  </>
);

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
Product.getInitialProps = async ({ query }) => {
  const res = await axiosProduction
    .get(`/Product/${query.id}`)
    .catch((error) => {
      console.error(error);
    });
  const data = await res?.data;

  return { data };
};
export default Product;
