import Head from 'next/head';
import React from 'react';

import { BestDeals } from '../components/pages/Home/BestDeals';
import { BestSellers } from '../components/pages/Home/BestSellers';
import { Hero } from '../components/pages/Home/Hero';
import { HeroHeader } from '../components/pages/Home/HeroHeader';
import { SpecialOffer } from '../components/pages/Home/SpecialOffer';
import { TabsComponent } from '../components/pages/Home/Tabs';
import { Footer } from '../components/shared/Footer';
import { Header } from '../components/shared/Header';
import { Category } from '../types/Category';
import { Product } from '../types/Product';

import axiosProduction, { axiosDev } from './api/axios';

const Home = ({
  products,
  categories,
}: {
  products: Product[];
  categories: Category[];
}) => (
  <>
    <Head>
      <title>Home</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main>
      <Header />
      <HeroHeader />

      <Hero categories={categories} />
      <div className="mx-auto mt-40 flex w-full max-w-[1400px] gap-[64px]">
        <SpecialOffer
          item={
            products && products[Math.floor(Math.random() * products.length)]
          }
        />
        <TabsComponent prods={products} />
      </div>
      <BestDeals data={products} categories={categories} />
      <BestSellers data={products} />
      <Footer categories={categories} />
    </main>
  </>
);
Home.getInitialProps = async () => {
  const res = await axiosDev.get('/Product/getall').catch((error) => {
    console.error(error);
  });
  const products = await res?.data.products;
  const categoriesRes = await axiosDev
    .get('/categorie/getall')
    .catch((error) => {
      console.error(error);
    });
  const categories = await categoriesRes?.data;

  return { products, categories };
};
export default Home;
