import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect } from 'react';

import { useGetUser } from '../../utils/hooks/useGetUser';
import { axiosPrivate } from '../api/axios';

const Success = () => {
  const router = useRouter();

  const { jwt } = useGetUser();
  const payOrder = async () => {
    if (router.query.orderId && jwt) {
      await axiosPrivate
        .patch(
          `/order/pay/${router.query.orderId}`,
          {},
          {
            headers: {
              Authorization: `Bearer ${jwt}`,
            },
          }
        )
        .then(() => router.push('/'))
        .catch(() => router.push('/'));
    }
  };

  useEffect(() => {
    if (router.query.orderId && !jwt) {
      // If JWT is not available, wait for it to be available
      const waitForJWT = async () => {
        await new Promise<void>((resolve) => {
          const interval = setInterval(() => {
            if (jwt) {
              clearInterval(interval);
              resolve();
            }
          }, 100); // Check every 100 milliseconds if JWT is available
        });
      };

      waitForJWT().then(() => payOrder());
    } else {
      payOrder();
    }
  }, [router.query.orderId, jwt]);

  return (
    <>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-[100vh] w-full items-center justify-center">
        Thanks for your Payment !!
      </main>
    </>
  );
};

export default Success;
